name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup npm
        uses: actions/setup-node@v4
        with:
          node-version: 20.17.0
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Check files
        run: npm run check

      #- name: Run tests
      #  run: npm run test
